// @ts-check
import { antfu } from "@antfu/eslint-config";

export default antfu(
  {
    stylistic: {
      semi: true,
      quotes: "double",
    },
    formatters: true,
  },
  {
    rules: {
      "antfu/if-newline": "off",
      "curly": ["error", "multi-line", "consistent"],
      "node/prefer-global/buffer": ["error", "always"],
      "node/prefer-global/process": ["error", "always"],
      "style/arrow-parens": ["error", "always"],
      "style/brace-style": ["error", "1tbs"],
      "style/operator-linebreak": ["error", "after", { overrides: { "?": "before", ":": "before" } }],
    },
  },
  {
    // Ignore generated files
    ignores: [
      ".pnpm-store/", // Generated by CI workflow
    ],
  },
);
