// @ts-check
const { antfu } = require("@antfu/eslint-config");

module.exports = antfu(
  {
    stylistic: {
      semi: true,
      quotes: "double",
    },
    formatters: true,
  },
  {
    rules: {
      "antfu/if-newline": "off",
      "curly": ["error", "multi-line", "consistent"],
      "no-console": "off",
      "node/prefer-global/buffer": ["error", "always"],
      "node/prefer-global/process": ["error", "always"],
      "style/arrow-parens": ["error", "always"],
      "style/brace-style": ["error", "1tbs"],
      "style/operator-linebreak": ["error", "after", { overrides: { "?": "before", ":": "before" } }],
    },
  },
  {
    // Ignore generated files
    ignores: [
      "prisma/migrations/migration_lock.toml", // Generated by Prisma Migrate
      "src/drizzle/meta/", // Generated by Drizzle Kit
      ".pnpm-store/", // Generated by CI workflow
    ],
  },
);
