services:
  app:
    container_name: emily
    image: ghcr.io/ntut-npc/emily:0.1.1
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    env_file: emily.env

  migrate:
    image: ghcr.io/ntut-npc/emily-migrate:0.1.1
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    env_file: emily.env

  db:
    container_name: emily-db
    image: postgres:16-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    env_file: db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d emily"]
      interval: 5s
      timeout: 5s
      retries: 10
  adminer:
    container_name: emily-adminer
    image: adminer
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      VIRTUAL_HOST: emily-db.example.com
      LETSENCRYPT_HOST: emily-db.example.com
      LETSENCRYPT_EMAIL: you@example.com
    networks:
      - proxy
      - default

networks:
  proxy:
    name: proxy
    external: true