services:
  app:
    container_name: emily
    depends_on:
      - db
    build: .
    restart: unless-stopped

  # Connect to db with postgresql://postgres:password@db:5432/emily
  db:
    container_name: emily-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password

  # Connect to adminer with http://emily-db.example.com/
  adminer:
    container_name: emily-adminer
    image: adminer
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=emily-db.example.com
      - LETSENCRYPT_HOST=emily-db.example.com
      - LETSENCRYPT_EMAIL=you@example.com
    networks:
      - proxy
      - default

networks:
  proxy:
    name: proxy
    external: true
