services:
  app:
    container_name: emily
    depends_on:
      - db
    build: .
    restart: unless-stopped

  # Connect to db with postgresql://postgres:password@db:5432/emily
  db:
    container_name: emily-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
