version: "3.8"
services:
  app:
    container_name: emily
    build: .
    restart: unless-stopped

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
